#!/usr/bin/bash

# Install required packages for tuqueOS image

dnf group install -y \
    "Graphical Administration Tools" \
    "System Tools" \
    "Virtualization Hypervisor" \
    "Container Management" \
    "Guest Desktop Agents" \
    "Guest Agents" \
    "Server with GUI" \
    "Multimedia" \
    "Fonts"

dnf install -y \
    -x gnome-extensions-app \
    gnome-tweaks \
    distrobox \
    vim-enhanced \
    samba \
    ntfs-3g \
    ntfsprogs \
    fuse-sshfs \
    git \
    chromium \
    xdg-desktop-portal \
    xdg-desktop-portal-gnome \
    xdg-desktop-portal-gtk \
    gnome-shell-extension-dash-to-dock \
    gnome-shell-extension-just-perfection \
    gnome-shell-extension-appindicator \
    gnome-shell-extension-blur-my-shell \
    gnome-shell-extension-logo-menu \
    ffmpeg-free \
    flac \
    faad2 \
    lame \
    libmad \
    vorbis-tools \
    libgcc \
    fonts-filesystem \
    google-noto-fonts-common \
    google-noto-sans-vf-fonts \
    redhat-text-vf-fonts \
    linux-firmware-whence \
    hwdata \
    tzdata \
    redhat-mono-vf-fonts \
    xkeyboard-config \
    default-fonts-core-sans \
    google-noto-sans-mono-vf-fonts \
    google-noto-serif-vf-fonts \
    google-noto-sans-devanagari-vf-fonts \
    mesa-filesystem \
    hunspell-filesystem \
    gnome-control-center-filesystem \
    google-noto-sans-bengali-vf-fonts \
    google-noto-sans-hebrew-vf-fonts \
    google-noto-sans-mono-cjk-vf-fonts \
    mozilla-filesystem \
    mobile-broadband-provider-info \
    hyperv-daemons-license \
    foomatic-db-filesystem \
    appstream-data \
    adobe-mappings-cmap \
    vim-data \
    pcre2-syntax \
    adobe-mappings-cmap-deprecated \
    google-noto-sans-cjk-vf-fonts \
    default-fonts-he \
    default-fonts-yi \
    default-fonts-as \
    default-fonts-bn \
    default-fonts-hi \
    default-fonts-mai \
    default-fonts-mr \
    langpacks-fonts-en \
    langpacks-core-en \
    osinfo-db \
    amd-ucode-firmware \
    atheros-firmware \
    brcmfmac-firmware \
    cirrus-audio-firmware \
    intel-audio-firmware \
    intel-vsc-firmware \
    mt7xxx-firmware \
    nxpwireless-firmware \
    realtek-firmware \
    tiwilink-firmware \
    amd-gpu-firmware \
    intel-gpu-firmware \
    nvidia-gpu-firmware \
    linux-firmware \
    default-fonts-ast \
    default-fonts-be \
    default-fonts-bg \
    default-fonts-br \
    default-fonts-dz \
    default-fonts-el \
    default-fonts-eo \
    default-fonts-eu \
    default-fonts-ia \
    default-fonts-ku \
    default-fonts-nb \
    default-fonts-nn \
    default-fonts-nr \
    default-fonts-nso \
    default-fonts-ru \
    default-fonts-ss \
    default-fonts-tn \
    default-fonts-ts \
    default-fonts-uk \
    default-fonts-ve \
    default-fonts-vi \
    default-fonts-xh \
    default-fonts-zu \
    google-droid-sans-fonts \
    google-noto-naskh-arabic-vf-fonts \
    google-noto-sans-arabic-vf-fonts \
    default-fonts-ar \
    google-noto-sans-armenian-vf-fonts \
    default-fonts-hy \
    google-noto-sans-canadian-aboriginal-vf-fonts \
    default-fonts-iu \
    google-noto-sans-cherokee-vf-fonts \
    default-fonts-chr \
    google-noto-sans-ethiopic-vf-fonts \
    default-fonts-am \
    google-noto-sans-georgian-vf-fonts \
    default-fonts-ka \
    google-noto-sans-gujarati-vf-fonts \
    default-fonts-gu \
    google-noto-sans-gurmukhi-vf-fonts \
    default-fonts-pa \
    google-noto-sans-kannada-vf-fonts \
    default-fonts-kn \
    google-noto-sans-khmer-vf-fonts \
    default-fonts-km \
    google-noto-sans-lao-vf-fonts \
    default-fonts-lo \
    google-noto-sans-math-fonts \
    google-noto-sans-meetei-mayek-vf-fonts \
    default-fonts-mni \
    google-noto-sans-ol-chiki-vf-fonts \
    default-fonts-sat \
    google-noto-sans-oriya-vf-fonts \
    default-fonts-or \
    google-noto-sans-sinhala-vf-fonts \
    default-fonts-si \
    google-noto-sans-symbols-2-fonts \
    google-noto-sans-symbols-vf-fonts \
    google-noto-sans-tamil-vf-fonts \
    default-fonts-ta \
    google-noto-sans-telugu-vf-fonts \
    default-fonts-te \
    google-noto-sans-thaana-vf-fonts \
    default-fonts-dv \
    google-noto-sans-thai-vf-fonts \
    default-fonts-th \
    google-noto-serif-armenian-vf-fonts \
    google-noto-serif-bengali-vf-fonts \
    google-noto-serif-devanagari-vf-fonts \
    google-noto-serif-ethiopic-vf-fonts \
    google-noto-serif-georgian-vf-fonts \
    google-noto-serif-gujarati-vf-fonts \
    google-noto-serif-gurmukhi-vf-fonts \
    google-noto-serif-hebrew-vf-fonts \
    google-noto-serif-kannada-vf-fonts \
    google-noto-serif-khmer-vf-fonts \
    google-noto-serif-lao-vf-fonts \
    google-noto-serif-oriya-vf-fonts \
    google-noto-serif-sinhala-vf-fonts \
    google-noto-serif-tamil-vf-fonts \
    google-noto-serif-telugu-vf-fonts \
    google-noto-serif-thai-vf-fonts \
    dejavu-sans-mono-fonts \
    google-noto-color-emoji-fonts \
    google-noto-serif-cjk-vf-fonts \
    jomolhari-fonts \
    default-fonts-bo \
    liberation-fonts-common \
    liberation-mono-fonts \
    madan-fonts \
    default-fonts-ne \
    paktype-naskh-basic-fonts \
    default-fonts-ur \
    rit-meera-new-fonts \
    default-fonts-ml \
    rit-rachana-fonts \
    sil-padauk-fonts \
    default-fonts-my \
    stix-fonts \
    vazirmatn-vf-fonts \
    default-fonts-fa \
    yelp-xsl \
    qemu-kvm-docs \
    poppler-data \
    mutter-common \
    llvm-filesystem \
    libwacom-data \
    liblouis-tables \
    libX11-common \
    kernel-headers \
    hplip-common \
    gawk-all-langpacks \
    emacs-filesystem \
    edk2-aarch64 \
    cmake-filesystem \
    centos-indexhtml \
    catatonit \
    bind-license \
    adwaita-cursor-theme \
    adobe-mappings-pdf \
    vim-filesystem \
    quota-nls \
    publicsuffix-list-dafsa \
    pkgconf-m4 \
    ncurses-base \
    libssh-config \
    kbd-misc \
    kbd-legacy \
    fuse-common \
    firewalld-filesystem \
    dnf-data \
    coreutils-common \
    centos-gpg-keys \
    centos-stream-repos \
    centos-stream-release \
    setup \
    filesystem \
    urw-base35-fonts-common \
    efi-filesystem \
    basesystem \
    glibc-all-langpacks \
    glibc-gconv-extra \
    glibc-common \
    glibc \
    ncurses-libs \
    bash \
    libstdc++ \
    zlib-ng-compat \
    libuuid \
    libzstd \
    popt \
    libblkid \
    xz-libs \
    libxml2 \
    sqlite-libs \
    readline \
    libjpeg-turbo \
    elfutils-libelf \
    libpng \
    libcap-ng \
    audit-libs \
    pcre2 \
    libcom_err \
    libtalloc \
    keyutils-libs \
    libxcrypt \
    grep \
    bzip2-libs \
    libseccomp \
    alsa-lib \
    nspr \
    libunistring \
    expat \
    alternatives \
    json-c \
    libtevent \
    libicu \
    libffi \
    libwayland-client \
    libtdb \
    libxkbcommon \
    gmp \
    jansson \
    libgpg-error \
    fribidi \
    lcms2 \
    libidn2 \
    nss-util \
    fuse3-libs \
    libnl3 \
    libX11-xcb \
    crypto-policies \
    libmnl \
    libref_array \
    hicolor-icon-theme \
    gdbm-libs \
    cyrus-sasl-lib \
    libattr \
    libacl \
    libbasicobjects \
    libcollection \
    libdhash \
    libtasn1 \
    p11-kit \
    libtool-ltdl \
    libassuan \
    mpfr \
    gawk \
    libsss_idmap \
    libaio \
    liburing \
    lz4-libs \
    libXau \
    libxcb \
    libX11 \
    libXext \
    libXfixes \
    libXi \
    libXrender \
    libXrandr \
    libXtst \
    libXdamage \
    libXinerama \
    libepoxy \
    libogg \
    opus \
    libvorbis \
    libxslt \
    libsigc++30 \
    grub2-common \
    libedit \
    libgomp \
    libsepol \
    libselinux \
    sed \
    libmount \
    libselinux-utils \
    findutils \
    libsemanage \
    libyaml \
    lua-libs \
    pciutils-libs \
    protobuf-c \
    sg3_utils-libs \
    boost-system \
    pixman \
    llvm-libs \
    libXcursor \
    libXcomposite \
    p11-kit-trust \
    gnutls \
    glib2 \
    json-glib \
    graphene \
    gsettings-desktop-schemas \
    libsecret \
    gcr-libs \
    gobject-introspection \
    shared-mime-info \
    gdk-pixbuf2 \
    libnotify \
    gvfs-client \
    libudisks2 \
    ModemManager-glib \
    nbdkit-server \
    libmbim \
    libportal \
    fuse3 \
    libgcrypt \
    libwayland-cursor \
    libfdisk \
    file-libs \
    hunspell-en-GB \
    hunspell-en-US \
    hunspell \
    dbus-common \
    bluez-libs \
    dmidecode \
    libeconf \
    pam-libs \
    shadow-utils \
    libcap \
    systemd-libs \
    openssl-fips-provider \
    openssl-libs \
    coreutils \
    ca-certificates \
    dbus-libs \
    polkit-libs \
    libgudev \
    libusb1 \
    kmod-libs \
    libblockdev-utils \
    libarchive \
    tpm2-tss \
    NetworkManager-libnm \
    kmod \
    centos-logos \
    libevent \
    avahi-libs \
    openldap \
    avahi-glib \
    gzip \
    libsss_certmap \
    libnvme \
    libnghttp2 \
    libsmartcols \
    util-linux-core \
    fdk-aac-free \
    libdvdread \
    libwebp \
    orc \
    libblockdev \
    libgusb \
    colord-libs \
    which \
    procps-ng \
    bubblewrap \
    libxmlb \
    libqrtr-glib \
    glibmm2.68 \
    libxkbfile \
    libmpc \
    libibverbs \
    libpcap \
    libical \
    keyutils \
    e2fsprogs-libs \
    libbpf \
    xml-common \
    iso-codes \
    libatomic \
    numactl-libs \
    qemu-img \
    libbrotli \
    libpciaccess \
    libdrm \
    libverto \
    krb5-libs \
    libtirpc \
    libcurl \
    appstream \
    cyrus-sasl-gssapi \
    lmdb-libs \
    libldb \
    lzo \
    make \
    userspace-rcu \
    gsm \
    lame-libs \
    libevdev \
    plymouth-core-libs \
    libexif \
    libglvnd \
    libieee1284 \
    libwayland-egl \
    libxshmfence \
    openjpeg2 \
    plymouth-graphics-libs \
    curl \
    libnfsidmap \
    libssh \
    libvirt-libs \
    libvirt-client \
    libvirt-daemon-lock \
    libvirt-daemon-log \
    libwinpr \
    libical-glib \
    nmap-ncat \
    cpp \
    libqmi \
    cracklib \
    dbus-tools \
    libjose \
    libtpms \
    net-snmp-libs \
    dbus-broker \
    dbus \
    dconf \
    PackageKit-glib \
    ibus-libs \
    libcamera-ipa \
    libcamera \
    shadow-utils-subid \
    enchant2 \
    file \
    gcr3-base \
    gtk-update-icon-cache \
    pinentry \
    libgtop2 \
    nautilus-extensions \
    ledmon-libs \
    tar \
    xmlsec1 \
    flac-libs \
    libtheora \
    gettext-libs \
    attr \
    ethtool \
    libnftnl \
    libpsl \
    libksba \
    groff-base \
    exempi \
    unzip \
    xz \
    libv4l \
    snappy \
    spirv-tools-libs \
    mesa-libgbm \
    mesa-dri-drivers \
    libglvnd-egl \
    mesa-libEGL \
    libglvnd-gles \
    webrtc-audio-processing \
    adwaita-icon-theme \
    cpio \
    diffutils \
    duktape \
    efivar-libs \
    inih \
    libpath_utils \
    libini_config \
    libtraceevent \
    npth \
    slang \
    dotconf \
    gutenprint-libs \
    jbig2dec-libs \
    libICE \
    libei \
    liblc3 \
    m4 \
    mpg123-libs \
    libsndfile \
    speex \
    libshout \
    bison \
    flex \
    libSM \
    newt \
    sscg \
    inih-cpp \
    exiv2 \
    exiv2-libs \
    libgexiv2 \
    mokutil \
    libproxy \
    glib-networking \
    libsoup3 \
    geocode-glib \
    libgweather \
    geoclue2 \
    geoclue2-libs \
    osinfo-db-tools \
    libosinfo \
    rest \
    vulkan-loader \
    mesa-vulkan-drivers \
    zip \
    ima-evm-utils \
    xmlsec1-openssl \
    pinentry-gnome3 \
    xdg-dbus-proxy \
    dbus-daemon \
    swtpm-libs \
    jose \
    cracklib-dicts \
    libpwquality \
    libqmi-utils \
    libvirt-daemon-proxy \
    nbdkit-ssh-plugin \
    sssd-nfs-idmap \
    lzop \
    nbdkit-curl-plugin \
    tpm2-tss-fapi \
    tpm2-tools \
    quota \
    libdex \
    libblockdev-fs \
    librdmacm \
    librados2 \
    xkbcomp \
    libdvdnav \
    libblockdev-nvme \
    libsane-airscan \
    libblockdev-loop \
    pciutils \
    usbredir \
    python3-pip-wheel \
    ldns \
    openssl \
    sound-theme-freedesktop \
    urw-base35-bookman-fonts \
    urw-base35-c059-fonts \
    urw-base35-d050000l-fonts \
    urw-base35-gothic-fonts \
    urw-base35-nimbus-mono-ps-fonts \
    urw-base35-nimbus-roman-fonts \
    urw-base35-nimbus-sans-fonts \
    urw-base35-p052-fonts \
    urw-base35-standard-symbols-ps-fonts \
    urw-base35-z003-fonts \
    urw-base35-fonts \
    pkcs11-provider \
    rpm-sequoia \
    rpm-plugin-audit \
    rpm-libs \
    libmodulemd \
    libsolv \
    rpm \
    color-filesystem \
    librepo \
    libdnf \
    rpm-sign-libs \
    rpm-plugin-systemd-inhibit \
    composefs-libs \
    librelp \
    scrub \
    sequoia-sq \
    device-mapper-persistent-data \
    conmon \
    libatasmart \
    libblockdev-smart \
    liboeffis \
    kbd \
    hunspell-en \
    libmbim-utils \
    nbdkit-basic-filters \
    nbdkit-basic-plugins \
    libgsf \
    desktop-file-utils \
    gnome-menus \
    libgee \
    libslirp \
    low-memory-monitor \
    libnbd \
    qpdf-libs \
    boost-thread \
    erofs-utils \
    fftw-libs-single \
    libXres \
    libXv \
    libXxf86vm \
    libglvnd-glx \
    mesa-libGL \
    libva \
    libXpm \
    xprop \
    at-spi2-core \
    atk \
    at-spi2-atk \
    libxkbcommon-x11 \
    xcb-util \
    startup-notification \
    zstd \
    libbytesize \
    p11-kit-server \
    acl \
    gdbm \
    pam \
    authselect-libs \
    cryptsetup-libs \
    device-mapper-libs \
    device-mapper \
    elfutils-debuginfod-client \
    elfutils-libs \
    elfutils-default-yama-scope \
    libutempter \
    systemd-pam \
    util-linux \
    systemd \
    polkit \
    polkit-pkla-compat \
    policycoreutils \
    qemu-kvm-common \
    selinux-policy \
    selinux-policy-targeted \
    cups-filesystem \
    cups-libs \
    logrotate \
    samba-common \
    libwbclient \
    samba-common-libs \
    samba-client-libs \
    libsmbclient \
    colord \
    binutils-gold \
    binutils \
    accountsservice \
    accountsservice-libs \
    bluez \
    device-mapper-event-libs \
    cups-client \
    container-selinux \
    passt-selinux \
    passt \
    qemu-kvm-device-display-virtio-gpu \
    bolt \
    cronie-anacron \
    cronie \
    crontabs \
    iputils \
    openssh \
    device-mapper-multipath-libs \
    kpartx \
    parted \
    librbd1 \
    qemu-kvm-block-rbd \
    device-mapper-multipath \
    qemu-pr-helper \
    qemu-kvm-device-display-virtio-gpu-pci \
    gutenprint \
    device-mapper-event \
    lvm2-libs \
    lvm2 \
    libblockdev-lvm \
    udisks2-lvm2 \
    bluez-obexd \
    cups-pk-helper \
    adcli-selinux \
    adcli \
    cockpit-ws-selinux \
    smartmontools-selinux \
    qemu-kvm-device-usb-host \
    qemu-kvm-device-usb-redirect \
    virtiofsd \
    ModemManager \
    rtkit \
    initscripts-service \
    audit-rules \
    audit \
    libkcapi \
    libkcapi-hasher \
    libkcapi-hmaccalc \
    lockdev \
    mdadm \
    libblockdev-mdraid \
    rpcbind \
    systemd-container \
    wpa_supplicant \
    flatpak-session-helper \
    hypervkvpd \
    hypervvssd \
    iio-sensor-proxy \
    virt-what \
    libblockdev-part \
    libblockdev-swap \
    makedumpfile \
    rpm-build-libs \
    libbabeltrace \
    cryptsetup \
    libluksmeta \
    luksmeta \
    ipset-libs \
    iw \
    nss-softokn-freebl \
    nss-softokn \
    nss-sysinit \
    nss \
    libsrtp \
    nss-tools \
    volume_key-libs \
    libblockdev-crypto \
    libwayland-server \
    libcomps \
    libipa_hbac \
    alsa-ucm \
    bzip2 \
    libss \
    e2fsprogs \
    editorconfig-libs \
    pigz \
    libfontenc \
    taglib \
    graphite2 \
    freetype \
    harfbuzz \
    fontconfig \
    cairo \
    cairo-gobject \
    gjs \
    cairomm1.16 \
    libXft \
    libXfont2 \
    libconfig \
    boost-atomic \
    boost-filesystem \
    libasan \
    libcdio \
    liblerc \
    libubsan \
    opencsd \
    soundtouch \
    tbb \
    dyninst \
    systemtap-runtime \
    hostname \
    kernel-tools-libs \
    less \
    mtools \
    numad \
    xdg-user-dirs \
    ncurses \
    perl-Digest \
    perl-Digest-MD5 \
    perl-B \
    perl-FileHandle \
    perl-Data-Dumper \
    perl-libnet \
    perl-AutoLoader \
    perl-URI \
    perl-Text-Tabs+Wrap \
    perl-if \
    perl-locale \
    perl-IO-Socket-IP \
    perl-Time-Local \
    perl-File-Path \
    perl-IO-Socket-SSL \
    perl-Net-SSLeay \
    perl-Pod-Escapes \
    perl-Mozilla-CA \
    perl-Class-Struct \
    perl-Term-ANSIColor \
    perl-POSIX \
    perl-IPC-Open3 \
    perl-File-Temp \
    perl-Term-Cap \
    perl-Pod-Simple \
    perl-HTTP-Tiny \
    perl-Socket \
    perl-SelectSaver \
    perl-Symbol \
    perl-File-stat \
    perl-podlators \
    perl-Pod-Perldoc \
    perl-Fcntl \
    perl-Text-ParseWords \
    perl-base \
    perl-mro \
    perl-IO \
    perl-overloading \
    perl-Pod-Usage \
    perl-Errno \
    perl-File-Basename \
    perl-Getopt-Std \
    perl-MIME-Base64 \
    perl-Scalar-List-Utils \
    perl-constant \
    perl-Storable \
    perl-overload \
    perl-parent \
    perl-vars \
    perl-Getopt-Long \
    perl-Carp \
    perl-Exporter \
    perl-NDBM_File \
    perl-PathTools \
    perl-DynaLoader \
    perl-Encode \
    perl-libs \
    perl-interpreter \
    perl-File-Find \
    perl-Math-Complex \
    perl-Math-BigInt \
    perl-DBI \
    perl-DBD-SQLite \
    psmisc \
    iproute \
    memstrack \
    c-ares \
    dosfstools \
    exfatprogs \
    fuse-libs \
    gettext-envsubst \
    gettext-runtime \
    grub2-tools-minimal \
    gettext \
    hdparm \
    isns-utils-libs \
    iscsi-initiator-utils-iscsiuio \
    iscsi-initiator-utils \
    udisks2-iscsi \
    libcbor \
    libfido2 \
    grubby \
    systemd-udev \
    dracut \
    os-prober \
    grub2-tools \
    kernel-modules-core \
    kernel-core \
    openssh-clients \
    kernel-modules \
    kernel-modules-extra \
    plymouth \
    plymouth-scripts \
    ipp-usb \
    sane-airscan \
    ipset \
    systemtap-client \
    dracut-squash \
    wireless-regdb \
    flashrom \
    libmtp \
    mdevctl \
    libdaemon \
    avahi \
    cups-ipptool \
    libev \
    libverto-libev \
    gssproxy \
    libndp \
    NetworkManager \
    NetworkManager-wifi \
    NetworkManager-wwan \
    libnfnetlink \
    libnetfilter_conntrack \
    iptables-libs \
    nftables \
    iptables-nft \
    iproute-tc \
    libvirt-daemon-common \
    libvirt-daemon-driver-nwfilter \
    libvirt-daemon-config-nwfilter \
    libvirt-daemon-driver-interface \
    libvirt-daemon-driver-nodedev \
    libvirt-daemon-driver-secret \
    libvirt-daemon-plugin-lockd \
    libvirt-daemon \
    libpipeline \
    libpkgconf \
    pkgconf \
    pkgconf-pkg-config \
    libzstd-devel \
    zlib-ng-compat-devel \
    elfutils-libelf-devel \
    fwupd-efi \
    elfutils-debuginfod-client-devel \
    libxcrypt-devel \
    glibc-devel \
    gcc \
    mallard-rng \
    openssl-devel \
    kernel-devel \
    xz-devel \
    elfutils-devel \
    libsss_nss_idmap \
    sssd-client \
    libsss_sudo \
    sssd-common \
    sssd-krb5-common \
    sssd-common-pac \
    sssd-krb5 \
    sssd-ldap \
    sssd-proxy \
    mpdecimal \
    python-unversioned-command \
    python3 \
    python3-libs \
    gstreamer1 \
    python3-dbus \
    python3-gobject-base-noarch \
    python3-gobject-base \
    cockpit-bridge \
    PackageKit \
    libwacom \
    unbound-anchor \
    unbound-libs \
    python3-six \
    python3-libselinux \
    upower \
    upower-libs \
    python3-libdnf \
    python3-hawkey \
    python3-attrs \
    python3-charset-normalizer \
    python3-idna \
    python3-libxml2 \
    python3-pyyaml \
    python3-rpds-py \
    python3-referencing \
    python3-rpm \
    python3-systemd \
    xfsprogs \
    udisks2 \
    python3-argcomplete \
    python3-audit \
    python3-lxml \
    switcheroo-control \
    python3-jsonschema-specifications \
    python3-jsonschema \
    kernel-tools \
    itstool \
    python3-urllib3 \
    python3-requests \
    python3-libsemanage \
    python3-dateutil \
    libstoragemgmt \
    python3-libstoragemgmt \
    gnutls-dane \
    gnutls-utils \
    libreswan \
    cockpit-packagekit \
    python3-dasbus \
    python3-libcomps \
    python3-dnf \
    dnf \
    kpatch-dnf \
    python3-dnf-plugins-core \
    python3-perf \
    sudo \
    sudo-python-plugin \
    cockpit-ws \
    nfs-utils \
    libvirt-daemon-driver-storage-core \
    libvirt-daemon-driver-storage-disk \
    libvirt-daemon-driver-storage-iscsi \
    libvirt-daemon-driver-storage-logical \
    libvirt-daemon-driver-storage-mpath \
    libvirt-daemon-driver-storage-rbd \
    libvirt-daemon-driver-storage-scsi \
    libvirt-daemon-driver-storage \
    python3-inotify \
    python3-linux-procfs \
    python3-nftables \
    python3-firewall \
    python3-packaging \
    python3-ply \
    python3-pycparser \
    python3-cffi \
    python3-cryptography \
    python3-ptyprocess \
    python3-pexpect \
    python3-pyudev \
    tuned \
    tuned-ppd \
    python3-setools \
    python3-setuptools \
    libcap-ng-python3 \
    python3-cairo \
    python3-gobject \
    python3-pyatspi \
    python3-cups \
    python3-distro \
    python3-file-magic \
    sos \
    python3-libvirt \
    libvirt-client-qemu \
    python3-pam \
    python3-speechd \
    systemtap-devel \
    qemu-kvm-tools \
    wsdd \
    gvfs \
    nettle \
    dnsmasq \
    libvirt-daemon-driver-network \
    libvirt-daemon-config-network \
    oniguruma \
    jq \
    clevis-pin-tpm2 \
    clevis \
    clevis-luks \
    dracut-network \
    kexec-tools \
    kdump-utils \
    pcsc-lite-libs \
    pcsc-lite-ccid \
    pcsc-lite \
    gnupg2-smime \
    gnupg2 \
    gpgme \
    ostree-libs \
    flatpak-libs \
    libjcat \
    fwupd-plugin-flashrom \
    fwupd \
    gpgmepp \
    aardvark-dns \
    netavark \
    containers-common \
    capstone \
    checkpolicy \
    python3-policycoreutils \
    policycoreutils-python-utils \
    setroubleshoot-plugins \
    setroubleshoot-server \
    cockpit-system \
    cockpit-storaged \
    flatpak-selinux \
    nbdkit-selinux \
    nbdkit \
    swtpm \
    swtpm-selinux \
    swtpm-tools \
    libvirt-daemon-driver-qemu \
    fstrm \
    giflib \
    jbigkit-libs \
    libtiff \
    poppler \
    poppler-glib \
    poppler-cpp \
    poppler-utils \
    gd \
    libgphoto2 \
    sane-backends-drivers-cameras \
    sane-backends-libs \
    sane-backends \
    sane-backends-drivers-scanners \
    hplip-libs \
    libgxps \
    libXdmcp \
    liba52 \
    libasyncns \
    pulseaudio-libs \
    libcanberra \
    pulseaudio-libs-glib2 \
    gsound \
    freerdp-libs \
    libao \
    pcaudiolib \
    espeak-ng \
    speech-dispatcher \
    speech-dispatcher-espeak-ng \
    qemu-kvm-audio-pa \
    libblkio \
    qemu-kvm-block-blkio \
    libdatrie \
    libthai \
    pango \
    gstreamer1-plugins-base \
    librsvg2 \
    rsvg-pixbuf-loader \
    gdk-pixbuf2-modules \
    gstreamer1-plugins-bad-free-libs \
    librsvg2-tools \
    pangomm2.48 \
    plymouth-plugin-label \
    plymouth-plugin-two-step \
    plymouth-theme-spinner \
    libdisplay-info \
    libeis \
    libestr \
    libfastjson \
    rsyslog \
    libfdt \
    qemu-kvm-core \
    libijs \
    libiptcdata \
    libtracker-sparql \
    tracker \
    tracker-miners \
    libldac \
    liblouis \
    python3-louis \
    libmaxminddb \
    libmpeg2 \
    libmspack \
    open-vm-tools \
    libnet \
    criu \
    criu-libs \
    crun \
    containers-common-extra \
    podman \
    libpaper \
    libgs \
    ghostscript-tools-fonts \
    ghostscript-tools-printing \
    ghostscript \
    libcupsfilters \
    cups-browsed \
    cups-filters \
    cups-filters-driverless \
    cups \
    libppd \
    foomatic-db-ppds \
    foomatic-db \
    foomatic \
    libsamplerate \
    libsbc \
    wireplumber \
    wireplumber-libs \
    pipewire-libs \
    pipewire \
    pipewire-plugin-libcamera \
    xdg-desktop-portal \
    ibus-gtk3 \
    libcanberra-gtk3 \
    gtk3 \
    xdg-desktop-portal-gtk \
    gtk4 \
    libadwaita \
    gtksourceview5 \
    gvfs-goa \
    gnome-online-accounts \
    tecla \
    libnma-gtk4 \
    gnome-desktop3 \
    gnome-desktop4 \
    gnome-settings-daemon \
    xdg-desktop-portal-gnome \
    gnome-session \
    evolution-data-server-langpacks \
    evolution-data-server \
    libspelling \
    papers-libs \
    gnome-bluetooth-libs \
    libportal-gtk4 \
    gnome-autoar \
    ibus-setup \
    ibus \
    flatpak \
    gnome-software-fedora-langpacks \
    gnome-software \
    nautilus \
    papers-nautilus \
    papers-previewer \
    papers-thumbnailer \
    gnome-tour \
    colord-gtk4 \
    gcr \
    gtkmm4.0 \
    gcr3 \
    gnome-keyring \
    gnome-keyring-pam \
    gnome-color-manager \
    libdecor \
    libhandy \
    libnma \
    nm-connection-editor \
    libwnck3 \
    system-config-printer-libs \
    xdg-user-dirs-gtk \
    gnome-remote-desktop \
    pipewire-gstreamer \
    pipewire-jack-audio-connection-kit \
    pipewire-jack-audio-connection-kit-libs \
    pipewire-pulseaudio \
    gnome-bluetooth \
    gnome-control-center \
    libuv \
    bind-libs \
    bind-utils \
    sssd-ad \
    sssd-ipa \
    sssd \
    authselect \
    libvpx \
    libxcvt \
    xorg-x11-server-Xwayland \
    mtdev \
    libinput \
    mutter \
    pcre2-utf32 \
    brlapi \
    brltty \
    python3-brlapi \
    twolame-libs \
    vte-profile \
    vte291 \
    vte291-gtk4 \
    wavpack \
    gstreamer1-plugins-good \
    gdm \
    gnome-shell \
    gnome-session-wayland-session \
    xxd \
    vim-common \
    vim-enhanced \
    gnome-browser-connector \
    gnome-shell-extension-background-logo \
    gnome-initial-setup \
    ptyxis \
    orca \
    realmd \
    system-config-printer-udev \
    gnome-disk-utility \
    gnome-system-monitor \
    papers \
    gnome-text-editor \
    gnome-settings-daemon-server-defaults \
    gnome-characters \
    gnome-clocks \
    gnome-calculator \
    baobab \
    gnome-font-viewer \
    gstreamer1-plugins-bad-free \
    open-vm-tools-desktop \
    pipewire-alsa \
    pipewire-utils \
    alsa-utils \
    pnm2ppa \
    gutenprint-cups \
    cockpit-podman \
    buildah \
    gstreamer1-plugins-ugly-free \
    qemu-kvm \
    rsyslog-gnutls \
    rsyslog-gssapi \
    rsyslog-relp \
    plymouth-system-theme \
    blktrace \
    PackageKit-gtk3-module \
    paps \
    libsane-hpaio \
    gvfs-gphoto2 \
    libvirt \
    cockpit \
    shim-aa64 \
    gvfs-fuse \
    gvfs-mtp \
    gvfs-smb \
    firewalld \
    dnf-plugins-core \
    kpatch \
    yum \
    NetworkManager-libreswan \
    yelp-tools \
    xfsdump \
    PackageKit-command-not-found \
    PackageKit-gstreamer-plugin \
    crypto-policies-scripts \
    usbutils \
    sssd-kcm \
    bash-completion \
    man-db \
    NetworkManager-bluetooth \
    NetworkManager-adsl \
    NetworkManager-tui \
    avahi-tools \
    kernel \
    grub2-efi-aa64 \
    grub2-tools-extra \
    dracut-config-rescue \
    rasdaemon \
    enscript \
    hyperv-daemons \
    smartmontools \
    openssh-server \
    samba-client \
    cifs-utils \
    at \
    chrony \
    net-tools \
    psacct \
    qemu-guest-agent \
    spice-vdagent \
    nvme-cli \
    strace \
    langpacks-en \
    rpm-plugin-selinux \
    efibootmgr \
    wget \
    nmap \
    lsof \
    irqbalance \
    tcpdump \
    openldap-clients \
    tmux \
    centos-backgrounds \
    initscripts-rename-device \
    zsh \
    rsync \
    ledmon \
    prefixdevname \
    bpftool \
    nano \
    sg3_utils \
    vim-minimal \
    grub2-efi-aa64-cdboot \
    plocate \
    cyrus-sasl-plain \
    mtr \
    man-pages \
    bc \
    lshw \
    ed \
    dos2unix \
    libsysfs \
    lsscsi \
    setserial \
    symlinks \
    time \
    tree \
    default-fonts-other-sans \
    default-fonts-core-math \
    default-fonts-other-serif \
    default-fonts-cjk-serif \
    default-fonts-core-emoji \
    dejavu-sans-fonts \
    default-fonts-cjk-sans \
    default-fonts-cjk-mono \
    default-fonts-core-serif \
    default-fonts-core-mono \
    default-fonts-other-mono \
    iwlwifi-dvm-firmware \
    iwlwifi-mvm-firmware \
    libertas-firmware \
    netronome-firmware \
    dejavu-serif-fonts \
    pt-sans-fonts \
    redhat-display-vf-fonts \
    gutenprint-doc \
    gnome-user-docs \
    bash-color-prompt \
    words \
    rootfiles \
    mailcap \
    NetworkManager-config-server

# Remove unwanted packages
dnf remove -y subscription-manager \
	setroubleshoot \
    firefox \
    firefox-langpacks